### ISSUE TITLE
tryGlob on isMonorepo declaration fails with ENOENT

### ISSUE THREAD

**Issue by ondrej-langr** [un-ts/pkgr#321]
Hey, I have stumbled upon some issue that may not be wanted. 

I have the workspaces field in package.json and I have listed matches for folders that may or may not exist - eg: "packages/**". If I dont have one of them present in my file system then it fails on me like this: 
![image](https://user-images.githubusercontent.com/60289583/230036097-6c55a6e8-0695-4991-a04f-a2de2a5a9107.png)

When I look at the tiny-glob package I think that this behavior may be wanted (that it throws) and thats why I decided to write here.

I'm totally open to create PR here or bringing this convo into tiny-glob package if you think this is not issue that should not be addressed here.

Cheers ✌️

**Comment by JounQin** [comment]
It seems tiny-glob is lack of maintenance now, maybe we should migrate to a new glob lob.
