### ISSUE TITLE
[oom] out of memory

### ISSUE THREAD

**Issue by tjx666** [un-ts/pkgr#329]
After I debug, I find the oom is caused by code at:

![oom](https://user-images.githubusercontent.com/41773861/240169677-41cce323-2cee-4657-80ca-6eb2d4e1c67a.png)

more info: https://github.com/ota-meshi/eslint-plugin-json-schema-validator/issues/220

**Comment by JounQin** [comment]
Thanks for reporting, I'll take a look tomorrow.
