### ISSUE TITLE
rollup: the resolve plugin things when in monorepo setup

### ISSUE THREAD

**Issue by tunnckoCore** [un-ts/pkgr#40]
When you are in monorepo setup, you want to resolve from the source of your other packages, not their `module` field, which will be resolved only if it's bundled/build before the rollup run.

For example. You have 3 packages. Package `A` depends on package `C`. You want each of them to be bundled with its dependencies. So non of the packages will have any `dependencies` so zero-time installs.

Currently, when `rollup` is run in monorepo setup and see `C` inside the code of `A` it will try to resolve it from the `module` field of the `C` (e.g. `dist/index.esm.js`), which in the time of the run may or may not exist in the filesystem at all. 

So we need to fix that. I've done this a couple of times. You need to pass `customResolveOptions`. [Check more here](https://github.com/tunnckoCore/monorepo/blob/master/packages/rolldown/src/index.js#L150-L199).

I've done a lot in this space through the last few years, and a couple of times I'm repeating myself :D That's why I share.

**Comment by JounQin** [comment]
That's why I decide to migrate to `pnpm` soon which supports overriding fields in `publishConfig`.

https://pnpm.js.org/en/package_json#publishconfig

And for now, just adding a `tsc` build step before bundling is my workaround.

Will think about your cool solution also.

`customResolveOptions` is awesome for resolving `browser` mapping filed in package like https://github.com/axios/axios/blob/master/package.json#L71-L73 also.

**Comment by tunnckoCore** [comment]
Hoho, cool one! Thanks.

**Comment by tunnckoCore** [comment]
And yet, you may still need to use the `babel-plugin-module-resolver`. Not sure, I don't remember currently.

**Comment by JounQin** [comment]
Is that duplicate with `rollup-plugin-alias`?

**Comment by tunnckoCore** [comment]
Kind of. It wants the same thing as the `alias` of webpack, jest's `moduleNameMapper` and etc.

Btw, even if you use `pnpm` - that's you, and this CLI still needs to work for others that don't use `pnpm`.

**Comment by JounQin** [comment]
@tunnckoCore I forked `rollup-plugin-alias` to `@rxts/rollup-plugin-alias` a few days ago which should just work as webpack.

See https://github.com/rx-ts/rollup-plugin-alias/commit/dc1aea862289a2e170df73cfbcb0c0e9b0fe8af5

**Comment by tunnckoCore** [comment]
Yea, i've seen that, but not looked at the codebase yet. I'll check and try everything if working correctly.

_Hint (reminder for me): or if this not works, we probably may use `options.output.paths` :thinking: _

**Comment by JounQin** [comment]
`pnpm` is awesome.

https://github.com/un-ts/yocto-ttl-cache/blob/77c27408075b0a37fa567c6043aa3e6b568faf7d/package.json#L95-L102

https://unpkg.com/browse/yocto-ttl-cache@0.1.0/package.json
